[package]
name = "cfg_experiment"
version = "0.1.0"
authors = ["Nam Nguyen <nanguye@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.1"
